name: 'Setup Tox'
description: 'Setup Tox'
inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.10'
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions