repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-added-large-files
      - id: check-ast
      - id: check-toml
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: forbid-submodules
      - id: name-tests-test
      - id: no-commit-to-branch
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.3.0"
    hooks:
      - id: tox-ini-fmt
        args: [ "tox.ini" ]
  #- repo: https://github.com/pycqa/isort
  #  rev: 5.12.0
  #  hooks:
  #    - id: isort
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
