repos:
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.1.0"
    hooks:
      - id: tox-ini-fmt
        args: [ "tox.ini" ]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10
        args:
          - --target-version=py310