repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-added-large-files
      - id: check-ast
      - id: check-toml
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: check-docstring-first
      - id: forbid-submodules
      - id: name-tests-test
      - id: no-commit-to-branch
      - id: mixed-line-ending
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.3.0"
    hooks:
      - id: tox-ini-fmt
        args: [ "tox.ini" ]
  #- repo: https://github.com/pycqa/isort
  #  rev: 5.12.0
  #  hooks:
  #    - id: isort
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
