name: codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          pip install -r requirements_test.txt
          pytest tests -v --cov-report term --cov-report html:htmlcov --cov-report xml --cov=quantus
      - name: Upload
        uses:  codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml, coverage.xml

