name: codecov
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          pip install coverage pytest
          coverage run -m pytest
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          #files: ./lib.c.gcov
          token: ${{ secrets.CODECOV_TOKEN }}
          
          
