name: codecov

on: [ push, workflow_dispatch ]

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Fetch
        uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'

      - name: Install dependecies
        run: pip install -r requirements.txt -r requirements_test.txt

      - name: Test
        run: pytest tests --cov-report term --cov-report html:htmlcov --cov-report xml --cov=quantus -n auto
        env:
          TF_XLA_FLAGS: "--tf_xla_auto_jit=2 --tf_xla_cpu_global_jit"

      - name: Upload
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml, coverage.xml

