name: codecov
on: [pull_request]
jobs:
  run:
    #runs-on: ubuntu-latest
    #env:
    #  OS: ubuntu-latest
    #  PYTHON: '3.9'
    #steps:
    #- uses: checkout@v2
    #  with:
    #    fetch-depth: '2'

    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: 3.9
        
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m pytest
        #pip install pytest-cov
        #pytest --cov=./ --cov-report=xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          fail_ci_if_error: true
          #files: ./lib.c.gcov
          token: ${{ secrets.CODECOV_TOKEN }}
