name: codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          pip install coverage pytest
          pytest tests -v --cov-report term --cov-report html:htmlcov --cov-report xml --cov=quantus
          #coverage run -m pytest
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          #files: ./lib.c.gcov
          token: ${{ secrets.CODECOV_TOKEN }}
          
          
