name: codecov
on: [ push, workflow_dispatch ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-tox/
        with:
          python-version: ${{ matrix.python-version }}

      - name: Measure coverage.
        run: tox run -e coverage
        env:
          TF_XLA_FLAGS: "--tf_xla_auto_jit=2 --tf_xla_cpu_global_jit"

      - name: Upload
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml, coverage.xml