name: codecov
on: [ pull_request, workflow_dispatch ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tox-gh
        run: pip install tox-gh

      - name: Setup test environment
        run: tox run -e coverage --notest

      - name: Measure coverage.
        run: tox run -e coverage
        env:
          TF_XLA_FLAGS: "--tf_xla_auto_jit=2 --tf_xla_cpu_global_jit"

      - name: Upload
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml, coverage.xml