name: Python package

on:
  workflow_dispatch:
    inputs:
      index:
        type: choice
        description: Index to publish snapshot release to
        options:
          - Test PyPi
          - PyPi
        default: Test PyPi



jobs:
  build:
    runs-on: ubuntu-latest
    name: Pre Release
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: "3.10"
      - name: Install tox-gh
        run: pip install tox-gh
      - name: Setup test environment
        run: tox run --notest
      - name: Test with PyTest
        run: tox run
      - name: Test building package
        run: tox run -e build
      - name: Publish to Test PyPi
        if: ${{github.event.inputs.index == 'Test PyPi'}}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/simple/
      - name: Publish to PyPi
        if: ${{github.event.inputs.index == 'PyPi'}}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://pypi.org/simple/