# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements_test.txt

      #- name: Lint
      #  run: |
      #    # stop the build if there are Python syntax errors or undefined names
      #    flake8 quantus --count --select=E9,F63,F7,F82 --show-source --statistics --exclude nlp
      #
      #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #    flake8 quantus --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude nlp
      #
      #    # run mypy
      #    mypy quantus --exclude nlp
      #
      - name: Test with pytest
        run: pytest -s -v -n 2 -m "not nlp"
        env:
          TF_XLA_FLAGS: "--tf_xla_auto_jit=2 --tf_xla_cpu_global_jit"

      - name: Test importing Quantus
        run: |
          pip install .
          python -c "import quantus;quantus.available_metrics()"
